// pushScheduler.jss
// Scheduled APNs push jobs for Daily Challenge retention.
// Registered as side-effect import in server.js: import './pushScheduler.js';
//
// Schedule (America/Chicago):
//   9:00 AM  — morning push   (morningNotification)
//   2:00 PM  — afternoon push (afternoonNotification)
//   8:00 PM  — evening push   (eveningNotification)
//
// The notification copy is generated by Claude at 5 AM alongside the Daily
// Challenge itself and saved to daily_challenge_cache.json.
// This scheduler reads that cache and sends the pre-generated copy verbatim.
// It never generates new copy or calls Claude.

import cron from 'node-cron';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { sendPush } from './apnsService.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CACHE_PATH = path.join(__dirname, 'daily_challenge_cache.json');
const TOKENS_PATH = path.join(__dirname, 'push_tokens.json');

// ─── Cache reader ─────────────────────────────────────────────────────────────
// Handles both flat shape { id, philosopherId, ... }
// and accidentally-wrapped shape { challenge: { id, ... } }.

function readChallenge() {
    try {
        if (!fs.existsSync(CACHE_PATH)) return null;

        const raw = JSON.parse(fs.readFileSync(CACHE_PATH, 'utf8'));
        if (!raw) return null;

        const challenge =
            raw.challenge && typeof raw.challenge === 'object'
                ? raw.challenge
                : raw;

        if (!challenge.id || !challenge.philosopherId) return null;

        return challenge;
    } catch (err) {
        console.error('[PushScheduler] Challenge read error:', err.message);
        return null;
    }
}

function readTokens() {
    try {
        if (!fs.existsSync(TOKENS_PATH)) return {};
        return JSON.parse(fs.readFileSync(TOKENS_PATH, 'utf8'));
    } catch (err) {
        console.error('[PushScheduler] Token read error:', err.message);
        return {};
    }
}

// ─── Display name helper ──────────────────────────────────────────────────────
// philosopherName is stored in the cache, but this is a safe fallback.

function philosopherDisplayName(id) {
    const names = {
        aristotle: 'Aristotle',
        plato: 'Plato',
        nietzsche: 'Nietzsche',
        socrates: 'Socrates',
        jung: 'Carl Jung',
        aurelius: 'Marcus Aurelius',
    };

    return names[String(id).toLowerCase()] || 'The philosopher';
}

// ─── Grammar helper ───────────────────────────────────────────────────────────
// Correct possessive titles:
// Aristotle -> Aristotle's
// Plato -> Plato's
// Socrates -> Socrates'
// Marcus Aurelius -> Marcus Aurelius'

function possessiveName(name) {
    const clean = String(name || '').trim();

    if (!clean) return 'The philosopher’s';

    return clean.toLowerCase().endsWith('s')
        ? `${clean}'`
        : `${clean}'s`;
}

// ─── Core send function ───────────────────────────────────────────────────────

async function sendDailyPush(timeOfDay) {
    const challenge = readChallenge();

    if (!challenge) {
        console.log(`[PushScheduler] ${timeOfDay} — No valid cached challenge. Skipping.`);
        return;
    }

    const philosopherName =
        challenge.philosopherName ||
        philosopherDisplayName(challenge.philosopherId);

    const bodyKey =
        timeOfDay === 'morning'
            ? 'morningNotification'
            : timeOfDay === 'afternoon'
            ? 'afternoonNotification'
            : 'eveningNotification';

    const body = challenge[bodyKey]?.trim();

    if (!body) {
        console.log(`[PushScheduler] ${timeOfDay} — Missing ${bodyKey} in cache. Skipping.`);
        return;
    }

    // IMPORTANT:
    // These use backticks, not regular quotes.
    // Regular quotes would show the literal text "${philosopherName}".
    const title =
        timeOfDay === 'morning'
            ? `${philosopherName} enters the Agora.`
            : timeOfDay === 'afternoon'
            ? `${philosopherName} is waiting.`
            : `${possessiveName(philosopherName)} time in the Agora is almost over.`;

    const tokens = readTokens();
    const entries = Object.values(tokens);

    if (entries.length === 0) {
        console.log(`[PushScheduler] ${timeOfDay} — No registered tokens. Skipping.`);
        return;
    }

    console.log('──────────────────────────────────────────────');
    console.log(`[PushScheduler] ${timeOfDay} push`);
    console.log(`[PushScheduler] Challenge ID: ${challenge.id}`);
    console.log(`[PushScheduler] Challenge Date: ${challenge.date || 'unknown'}`);
    console.log(`[PushScheduler] Philosopher ID: ${challenge.philosopherId}`);
    console.log(`[PushScheduler] Philosopher name: ${philosopherName}`);
    console.log(`[PushScheduler] Title: ${title}`);
    console.log(`[PushScheduler] Body: ${body}`);
    console.log(`[PushScheduler] Token count: ${entries.length}`);
    console.log('──────────────────────────────────────────────');

    const challengePayload = {
        challengeId: challenge.id,
        challengeDate: challenge.date || '',
        philosopherId: challenge.philosopherId,
        philosopher: philosopherName,
    };

    let sent = 0;
    let skipped = 0;
    let failed = 0;

    for (const record of entries) {
        if (!record.deviceToken) {
            skipped++;
            continue;
        }

        if (record.notificationsEnabled === false) {
            skipped++;
            continue;
        }

        if (record.lastCompletedChallengeId === challenge.id) {
            skipped++;
            continue;
        }

        const ok = await sendPush(
            record.deviceToken,
            title,
            body,
            challengePayload
        );

        if (ok) {
            sent++;
        } else {
            failed++;
        }
    }

    console.log(
        `[PushScheduler] ${timeOfDay} — sent: ${sent}, skipped: ${skipped}, failed: ${failed}`
    );
}

// ─── Cron jobs America/Chicago ────────────────────────────────────────────────

cron.schedule(
    '0 9 * * *',
    () => {
        console.log('[PushScheduler] Firing morning push job');
        sendDailyPush('morning');
    },
    { timezone: 'America/Chicago' }
);

cron.schedule(
    '0 14 * * *',
    () => {
        console.log('[PushScheduler] Firing afternoon push job');
        sendDailyPush('afternoon');
    },
    { timezone: 'America/Chicago' }
);

cron.schedule(
    '0 20 * * *',
    () => {
        console.log('[PushScheduler] Firing evening push job');
        sendDailyPush('evening');
    },
    { timezone: 'America/Chicago' }
);

console.log('[PushScheduler] Cron jobs registered — 9 AM / 2 PM / 8 PM America/Chicago');
