-- 017_kierkegaard_unlock_now.sql
--
-- RETIRED BEFORE PRODUCTION APPLICATION on August 14, 2026.
--
-- The original version of this migration immediately unlocked Kierkegaard
-- using an obsolete August 2026 launch date. Production never applied migration
-- 017, so that behavior has been removed before this migration enters database
-- history.
--
-- This migration is intentionally inert. It exists only to preserve migration
-- version 017 so the normal migration runner can advance safely.
--
-- IMPORTANT:
--   * Do not unlock Kierkegaard from migration 017.
--   * Do not change Kierkegaard release dates from migration 017.
--   * Do not change Dostoevsky or any other philosopher from migration 017.
--   * Do not change Ranked configuration from migration 017.
--   * Kierkegaard's planned Open Access Weekend is September 11-13, 2026.
--   * The real Kierkegaard release configuration must be created in a NEW
--     forward migration using the next unused migration version after 018.
--
-- The migration runner wraps this file in a transaction. Do not add BEGIN or
-- COMMIT statements here.

SELECT 1 AS retired_migration_017;
